#!/bin/sh
export DISPLAY=:0.0
export XAUTHORITY=/home/antonio/.Xauthority

device=$(xinput list | grep "MOSART Semi. 2.4G Keyboard Mouse [^Consumer|System]*[a-z=0-9 ]*slave  pointer" | awk '{print $8;}' | sed 's/id=//')

xinput set-button-map $device 1 2 3 4 5 6 7 9 8
